--- #YAML:1.0
name:               HTML-Rainbow
version:            0.06
abstract:           Put colour into your HTML
author:
    - David Landgren
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Tie::Cycle::Sinewave:  0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
