--- #YAML:1.0
name:                HTML-Rainbow
version:             0.04
abstract:            Put colour into your HTML
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Tie::Cycle::Sinewave:          0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Landgren
